import type { Product } from './database.types';

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Executive Leather Compendium',
        description: 'A premium leather compendium perfect for corporate executives.',
        category: 'Corporate',
        price: 4500,
        compare_price: 6000,
        stock: 50,
        material: 'Genuine Leather',
        style: 'Classic',
        images: ['https://images.pexels.com/photos/264787/pexels-photo-264787.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Pen loop', 'Card slots', 'A4 notepad included'],
        dimensions: { width: 23, height: 32, depth: 3 },
        rating: 4.8,
        review_count: 124,
        is_featured: true,
        is_bestseller: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '2',
        name: 'Personalized Crystal Decanter Set',
        description: 'An elegant crystal decanter set that can be engraved with initials.',
        category: 'Personalized',
        price: 12500,
        compare_price: 15000,
        stock: 20,
        material: 'Lead-free Crystal',
        style: 'Modern',
        images: ['https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Set of 4 glasses', 'Custom engraving', 'Premium presentation box'],
        dimensions: { width: 40, height: 35, depth: 15 },
        rating: 4.9,
        review_count: 89,
        is_featured: true,
        is_bestseller: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '3',
        name: 'Festive Gourmet Hamper',
        description: 'A lavish hamper filled with curated artisanal chocolates and premium nuts.',
        category: 'Festive',
        price: 8500,
        compare_price: null,
        stock: 100,
        material: 'Wicker & Ribbon',
        style: 'Traditional',
        images: ['https://images.pexels.com/photos/1666070/pexels-photo-1666070.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Artisanal chocolates', 'Premium roasted nuts', 'Handcrafted truffles'],
        dimensions: { width: 35, height: 25, depth: 25 },
        rating: 4.7,
        review_count: 210,
        is_featured: false,
        is_bestseller: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '4',
        name: 'Bespoke Luxury Watch Box',
        description: 'A meticulously crafted box to store and display luxury timepieces.',
        category: 'Luxury Boxes',
        price: 18000,
        compare_price: 22000,
        stock: 15,
        material: 'Mahogany & Velvet',
        style: 'Luxury',
        images: ['https://images.pexels.com/photos/2790153/pexels-photo-2790153.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Holds 6 watches', 'Glass display top', 'Lock and key'],
        dimensions: { width: 30, height: 10, depth: 20 },
        rating: 5.0,
        review_count: 42,
        is_featured: true,
        is_bestseller: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '5',
        name: 'Custom Engraved Montblanc Pen',
        description: 'A legendary writing instrument personalized with a custom engraving.',
        category: 'Personalized',
        price: 25000,
        compare_price: null,
        stock: 5,
        material: 'Precious Resin',
        style: 'Timeless',
        images: ['https://images.pexels.com/photos/3727464/pexels-photo-3727464.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Gold-coated clip', 'Hand-crafted nib', 'Luxury gift box'],
        dimensions: { width: 2, height: 14, depth: 2 },
        rating: 4.9,
        review_count: 15,
        is_featured: true,
        is_bestseller: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '6',
        name: 'Executive Tech Organizer',
        description: 'Keep your digital life organized with this premium travel folio.',
        category: 'Corporate',
        price: 3500,
        compare_price: 4500,
        stock: 75,
        material: 'Vegan Leather',
        style: 'Minimalist',
        images: ['https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&w=800'],
        features: ['Cable management', 'Tablet pocket', 'Water resistant'],
        dimensions: { width: 25, height: 18, depth: 4 },
        rating: 4.6,
        review_count: 312,
        is_featured: false,
        is_bestseller: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];
